# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='spot_fx_md_1.proto',
  package='capitalk',
  serialized_pb='\n\x12spot_fx_md_1.proto\x12\x08\x63\x61pitalk\"\xc1\x01\n\x07order_t\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03mic\x18\x02 \x02(\t\x12\x0b\n\x03qid\x18\x03 \x02(\x05\x12&\n\x04side\x18\x04 \x02(\x0e\x32\x18.capitalk.order_t.side_t\x12\x0c\n\x04size\x18\x05 \x02(\x01\x12\r\n\x05price\x18\x06 \x02(\x01\"\x1a\n\x06side_t\x12\x07\n\x03\x42ID\x10\x00\x12\x07\n\x03\x41SK\x10\x01\"-\n\x0cquote_type_t\x12\x0e\n\nINDICATIVE\x10\x00\x12\r\n\tTRADEABLE\x10\x01\"p\n\x07mic_bbo\x12\x0b\n\x03mic\x18\x01 \x02(\t\x12\x0e\n\x06symbol\x18\x02 \x02(\t\x12\x10\n\x08\x62id_size\x18\x03 \x02(\x01\x12\x11\n\tbid_price\x18\x04 \x02(\x01\x12\x10\n\x08\x61sk_size\x18\x05 \x02(\x01\x12\x11\n\task_price\x18\x06 \x02(\x01\"\x86\x01\n\x0einstrument_bbo\x12\x0e\n\x06symbol\x18\x01 \x02(\t\x12\x0e\n\x06\x62\x62_mic\x18\x02 \x02(\t\x12\x10\n\x08\x62\x62_price\x18\x03 \x02(\x01\x12\x0f\n\x07\x62\x62_size\x18\x04 \x02(\x01\x12\x0e\n\x06\x62\x61_mic\x18\x05 \x02(\t\x12\x10\n\x08\x62\x61_price\x18\x06 \x02(\x01\x12\x0f\n\x07\x62\x61_size\x18\x07 \x02(\x01')



_ORDER_T_SIDE_T = descriptor.EnumDescriptor(
  name='side_t',
  full_name='capitalk.order_t.side_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ASK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=153,
  serialized_end=179,
)

_ORDER_T_QUOTE_TYPE_T = descriptor.EnumDescriptor(
  name='quote_type_t',
  full_name='capitalk.order_t.quote_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INDICATIVE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRADEABLE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=181,
  serialized_end=226,
)


_ORDER_T = descriptor.Descriptor(
  name='order_t',
  full_name='capitalk.order_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='capitalk.order_t.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mic', full_name='capitalk.order_t.mic', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qid', full_name='capitalk.order_t.qid', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='side', full_name='capitalk.order_t.side', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='capitalk.order_t.size', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='capitalk.order_t.price', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ORDER_T_SIDE_T,
    _ORDER_T_QUOTE_TYPE_T,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=226,
)


_MIC_BBO = descriptor.Descriptor(
  name='mic_bbo',
  full_name='capitalk.mic_bbo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mic', full_name='capitalk.mic_bbo.mic', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='symbol', full_name='capitalk.mic_bbo.symbol', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bid_size', full_name='capitalk.mic_bbo.bid_size', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bid_price', full_name='capitalk.mic_bbo.bid_price', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ask_size', full_name='capitalk.mic_bbo.ask_size', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ask_price', full_name='capitalk.mic_bbo.ask_price', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=228,
  serialized_end=340,
)


_INSTRUMENT_BBO = descriptor.Descriptor(
  name='instrument_bbo',
  full_name='capitalk.instrument_bbo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='symbol', full_name='capitalk.instrument_bbo.symbol', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bb_mic', full_name='capitalk.instrument_bbo.bb_mic', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bb_price', full_name='capitalk.instrument_bbo.bb_price', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bb_size', full_name='capitalk.instrument_bbo.bb_size', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ba_mic', full_name='capitalk.instrument_bbo.ba_mic', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ba_price', full_name='capitalk.instrument_bbo.ba_price', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ba_size', full_name='capitalk.instrument_bbo.ba_size', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=343,
  serialized_end=477,
)

_ORDER_T.fields_by_name['side'].enum_type = _ORDER_T_SIDE_T
_ORDER_T_SIDE_T.containing_type = _ORDER_T;
_ORDER_T_QUOTE_TYPE_T.containing_type = _ORDER_T;
DESCRIPTOR.message_types_by_name['order_t'] = _ORDER_T
DESCRIPTOR.message_types_by_name['mic_bbo'] = _MIC_BBO
DESCRIPTOR.message_types_by_name['instrument_bbo'] = _INSTRUMENT_BBO

class order_t(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDER_T
  
  # @@protoc_insertion_point(class_scope:capitalk.order_t)

class mic_bbo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MIC_BBO
  
  # @@protoc_insertion_point(class_scope:capitalk.mic_bbo)

class instrument_bbo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTRUMENT_BBO
  
  # @@protoc_insertion_point(class_scope:capitalk.instrument_bbo)

# @@protoc_insertion_point(module_scope)
